name: Build Compile
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run build
        run: yarn build
