name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ${{secrets.SSH_HOST}} | sed 's/./& /g'
            echo ${{secrets.SSH_USERNAME}} | sed 's/./& /g'
            echo ${{secrets.SSH_KEY}} | sed 's/./& /g'
            echo ${{secrets.SSH_PORT}} | sed 's/./& /g'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            pm2 stop main
            cd dq-store-be/
            git pull origin master
            yarn install
            yarn build
            yarn typeorm migration:run
            pm2 start main
